<?php

namespace EventBundle\Repository;

/**
 * BirthdayRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BirthdayRepository extends \Doctrine\ORM\EntityRepository
{
}
